version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'

    # further configurations possibilities https://stackoverflow.com/a/57825166
    environment:
      - MONGO_INITDB_DATABASE=glasshouse_dev
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
